name: Setup nix
description: Installs a specified version of nix
runs:
  using: composite
  steps:
  - name: Install nix
    uses: DeterminateSystems/nix-installer-action@v16
    with:
      # Commit corresponds to tag v0.30.0 and installs nix v2.24.0.
      source-revision: b4bc792f575248e63e92c95cd9d334d01ba86b71
      # Disable telemetry.
      diagnostic-endpoint: ""
