name: Build
on: workflow_call
permissions: {}
jobs:
  build:
    strategy:
      matrix:
        artifact:
        - name: datapack
          make-target: build-datapack
          path-prefix: enderman-block
    runs-on: ubuntu-24.04-arm
    name: ${{ matrix.artifact.name }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Build ${{ matrix.artifact.name }}
      run: nix develop .#build -c make ${{ matrix.artifact.make-target }}
    - name: Upload ${{ matrix.artifact.name }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: ${{ matrix.artifact.name }}
        path: ${{ matrix.artifact.path-prefix }}.zip
        include-hidden-files: true
        if-no-files-found: error
  checksums:
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
      with:
        merge-multiple: true
        path: artifacts
    - name: Generate artifact checksums
      working-directory: artifacts
      run: nix develop .#createChecksums -c sha256sum * >> ../checksums.txt
    - name: Upload checksums
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: checksums
        path: checksums.txt
        include-hidden-files: true
        if-no-files-found: error
