name: CI
on: [pull_request, workflow_dispatch, merge_group, workflow_call]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    permissions:
      security-events: write
  build:
    uses: ./.github/workflows/build.yml
