name: Dependency Review
on: [pull_request, merge_group]
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  dependency-review:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.11.0
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: github.com:443 api.github.com:443
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Dependency Review
      uses: actions/dependency-review-action@v4.5.0
