name: Dependency Review
on: [pull_request]
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.10.4
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          api.securityscorecards.dev:443
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Dependency Review
      uses: actions/dependency-review-action@v4.5.0
