name: Lint
on: workflow_call
permissions: {}
jobs:
  flake:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # v9
      with:
        send-statistics: false
        ignore-missing-flake-lock: false
        fail-mode: true
  checks:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Flake checks
      run: nix flake check --all-systems
  editorconfig:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Lint editorconfig
      run: nix develop .#lintEditorconfig -c editorconfig-checker -f github-actions
  workflows:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: ./.github/actions/setup-nix
    - name: Lint workflows
      run: nix develop .#lintWorkflows -c zizmor --format sarif . > workflow_results.sarif
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload workflow report
      uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
      with:
        sarif_file: workflow_results.sarif
        category: zizmor
