name: Lint
on: workflow_call
permissions: {}
jobs:
  flake:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.11.0
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          api.securityscorecards.dev:443
        #   cache.nixos.org:443
        #   tarballs.nixos.org:443
        #   install.determinate.systems:443
        #   api.flakehub.com:443
        #   static.rust-lang.org:443
        #   static.crates.io:443
        #   crates.io:443
        #   *.s3.dualstack.us-east-2.amazonaws.com:443
        #   *.cloudfront.net:443
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Setup nix
      uses: ./.github/actions/setup-nix
    - name: Lint flake
      uses: DeterminateSystems/flake-checker-action@v9
      with:
        # Disable telemetry.
        send-statistics: false
        ignore-missing-flake-lock: false
        fail-mode: true
  checks:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.11.0
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443 api.github.com:443 api.securityscorecards.dev:443
        #   cache.nixos.org:443
        #   tarballs.nixos.org:443
        #   install.determinate.systems:443
        #   api.flakehub.com:443
        #   static.rust-lang.org:443
        #   static.crates.io:443
        #   crates.io:443
        #   *.s3.dualstack.us-east-2.amazonaws.com:443
        #   *.cloudfront.net:443
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Setup nix
      uses: ./.github/actions/setup-nix
    - name: Flake checks
      run: nix flake check
  editorconfig:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.11.0
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          api.securityscorecards.dev:443
        #   cache.nixos.org:443
        #   tarballs.nixos.org:443
        #   install.determinate.systems:443
        #   api.flakehub.com:443
        #   static.rust-lang.org:443
        #   static.crates.io:443
        #   crates.io:443
        #   *.s3.dualstack.us-east-2.amazonaws.com:443
        #   *.cloudfront.net:443
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Setup nix
      uses: ./.github/actions/setup-nix
    - name: Lint editorconfig
      run: nix develop .#lintEditorconfig -c editorconfig-checker -f github-actions
  workflows:
    runs-on: ubuntu-24.04-arm
    permissions:
      security-events: write
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.11.0
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          api.securityscorecards.dev:443
        #   cache.nixos.org:443
        #   tarballs.nixos.org:443
        #   install.determinate.systems:443
        #   api.flakehub.com:443
        #   static.rust-lang.org:443
        #   static.crates.io:443
        #   crates.io:443
        #   *.s3.dualstack.us-east-2.amazonaws.com:443
        #   *.cloudfront.net:443
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Setup nix
      uses: ./.github/actions/setup-nix
    - name: Lint workflows
      run: nix develop .#lintWorkflows -c zizmor --format sarif . > workflow_results.sarif
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload workflow report
      uses: github/codeql-action/upload-sarif@v3.28.10
      with:
        sarif_file: workflow_results.sarif
        category: zizmor
