name: Lint
on:
  release:
    types: [published]
  pull_request: null
  workflow_dispatch: null
jobs:
  checks:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@v2.10.3
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          api.github.com:443
          cache.nixos.org:443
          tarballs.nixos.org:443
          install.determinate.systems:443
          api.flakehub.com:443
          static.rust-lang.org:443
          static.crates.io:443
          crates.io:443
          *.s3.dualstack.us-east-2.amazonaws.com:443
          *.cloudfront.net:443
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@v16
      with:
        # Commit corresponds to tag v0.30.0 and installs nix v2.24.0.
        source-revision: b4bc792f575248e63e92c95cd9d334d01ba86b71
        # Disable telemetry.
        diagnostic-endpoint: ""
    - name: Setup cache
      uses: DeterminateSystems/magic-nix-cache-action@v8
      with:
        # Commit does not correspond to a tag.
        source-revision: 296e9dc1af825f2c961c1caa61832609b1bf8a49
        # Disable telemetry.
        diagnostic-endpoint: ""
    - name: Check flake
      uses: DeterminateSystems/flake-checker-action@v9
      with:
        # Disable telemetry.
        send-statistics: false
        ignore-missing-flake-lock: false
        fail-mode: true
    - name: Check
      run: nix flake check -L
    - name: Check workflows
      run: nix develop .#zizmor -c zizmor --format sarif . > workflow_results.sarif
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload workflow report
      uses: github/codeql-action/upload-sarif@v3.28.1
      with:
        sarif_file: workflow_results.sarif
        category: zizmor
